### ISSUE TITLE
プロキシURLが公開されてしまっています；；

### ISSUE THREAD

**Issue by whale-yay** [YuSzmiya/dotfiles#1]
https://github.com/t4jet/dotfiles/blob/7de128b53cf865330f24de97f00abb2d390359d7/.zshrc#L33

他者に公開したくない変数は .envファイル(.gitignoreで無視する)に記入するようにしましょう；；

**Comment by t4jet** [comment]
ありがとうございます🙏
プロキシを保存する用のファイルを作って、そちらをgitignoreに含めようと思います。

**Comment by whale-yay** [comment]
対応ありがとうございます＠＠
